steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - .
      - -f
      - docker/Dockerfile.pybeam2stage
      - -t
      - 'us-west2-docker.pkg.dev/$PROJECT_ID/dataflow/pybeam-gcb:draft-v0'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/dataflow/pybeam-gcb:draft-v0'
