steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - build
    - .
    - -f
    - Dockerfile.pybeam
    - -t
    - 'us-west2-docker.pkg.dev/$PROJECT_ID/dataflow/pybeam-gcb:draft-v0'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/dataflow/pybeam-gcb:draft-v0'
