default:
    just --list

name := "efnlp"

all: build run

preproc:
	cmake CMakeLists.txt

codegen:
	protoc -I=proto --cpp_out=proto proto/efnlp.proto

compile:
	make

build: preproc compile

run *FLAGS:
	./efnlp {{FLAGS}}
