FROM apache/beam_python3.10_sdk AS base

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates curl cmake g++ build-essential \
        libprotobuf-dev protobuf-compiler \
        python3-dev python3-distutils \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 10
