services:

  # # envoy, configured as with envoy.yaml to use extprocs
  # envoy:
  #   image: envoyproxy/envoy:${ENVOY_VERSION:-v1.22-latest}
  #   ports:
  #     - "8080:8000"
  #     - "9901:9901"
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #   # turn on logging as needed; can be _very_ noisy otherwise esp. with trace
  #   logging:
  #     driver: none

  # server
  efnlp:
    hostname: efnlp
    image: efnlp-go:${IMAGE_TAG:-compose}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    volumes:
      - ../cpp:/app/data
    environment:
      - LOG_LEVEL=info
    command:
      - efnlp
      - -language=s3://efnlp-private/language.proto.bin.gz
      - -model=s3://efnlp-private/model.proto.bin.gz
      # - -language=/app/data/language.proto.bin
      # - -model=/app/data/model.proto.bin
