
format:
    go fmt

codegen:
    buf -v generate buf.build/envoyproxy/protoc-gen-validate \
    && buf -v generate --include-imports

build: codegen
    go build

run *FLAGS:
    go run *.go {{FLAGS}}

containerize IMAGE_TAG="local":
    docker build . -t efnlp-go:{{IMAGE_TAG}}

up *FLAGS:
    docker-compose build && docker-compose up {{FLAGS}}
